server:
  port: 9000
eureka:
  client:
    register-with-eureka: false # 是否将自己注册到注册中心
    fetch-registry: false # 是否要从eureka中获取注册中心
    service-url:
      defautZone: http://127.0.0.1:9000/eureka
spring:
  application:
    name: eureka-servwe
