
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.108:3306/url_exchange
    #url: jdbc:mysql://127.0.0.1:9306/website
    username: root
    #password:
    password: 123456
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
#  redis:
#    database: 0 # Redis数据库索引（默认为0）
#    host: 127.0.0.1 # Redis服务器地址
#    port: 6379 # Redis服务器连接端口
#    timeout: 1000 # 连接超时时间（毫秒）
#    #password:  # Redis服务器连接密码（默认为空）
#    jedis:
#      pool:
#        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9080


qr-code:
  #ip: http://192.168.0.185/
  ip : http://127.0.0.1:9000/
  rootPath: /home/url_exchange_nginx/web
  path: /pic/
  ext: PNG
  size: 350
